accounts/urls.py
from django.contrib.auth import views as auth_views
from django.urls import path

from . import views

app_name = "accounts"

urlpatterns = [
    path("signup/", views.SignupView.as_view(), name="signup"),
    path("login/", auth_views.LoginView.as_view(template_name="accounts/login.html"), name="login"),
    path("logout/", auth_views.LogoutView.as_view(), name="logout"),
    path("<str:username>/", views.UserProfileView.as_view(), name="user_profile"),
    # path('<str:username>/follow/', views.FollowView.as_view(), name='follow'),
    # path('<str:username>/unfollow/', views.UnFollowView, name='unfollow'),
    # path('<str:username>/following_list/', views.FollowingListView.as_view(), name='following_list'),
    # path('<str:username>/follower_list/', views.FollowerListView.as_view(), name='follower_list'),
]

mysite/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("admin/", admin.site.urls),
    path("accounts/", include("accounts.urls")),
    path("tweets/", include("tweets.urls")),
    path("", include("welcome.urls")),
]

tweets/urls.py
from django.urls import path

from . import views

app_name = "tweets"

urlpatterns = [
    path("home/", views.HomeView.as_view(), name="home"),
    path("create/", views.TweetCreateView.as_view(), name="create"),
    path("<int:pk>/", views.TweetDetailView.as_view(), name="detail"),
    path("<int:pk>/delete/", views.TweetDeleteView.as_view(), name="delete"),
    # path('<int:pk>/like/', views.LikeView, name='like'),
    # path('<int:pk>/unlike/', views.UnlikeView, name='unlike'),
]

welcome/urls.py
from django.urls import path

from . import views

app_name = "welcome"
urlpatterns = [
    path("", views.WelcomeView.as_view()),
]

accounts/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models


class User(AbstractUser):
    email = models.EmailField()


# class FriendShip(models.Model):

tweets/models.py
from django.db import models

from accounts.models import User


class Tweet(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    content = models.TextField(max_length=140)
    created_at = models.DateTimeField(auto_now_add=True)

welcome/models.py
# from django.db import models

# Create your models here.

accounts/forms.py
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import UserCreationForm

User = get_user_model()


class SignupForm(UserCreationForm):
    class Meta:
        model = User
        fields = ("username", "email")

tweets/forms.py
from django.forms import ModelForm

from tweets.models import Tweet


class CreateTweetForm(ModelForm):
    class Meta:
        model = Tweet
        fields = ("content",)

accounts/views.py
from django.contrib.auth import authenticate, login
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse_lazy
from django.views.generic import CreateView, TemplateView

from .forms import SignupForm


class SignupView(CreateView):
    form_class = SignupForm
    template_name = "accounts/signup.html"
    success_url = reverse_lazy("tweets:home")

    def form_valid(self, form):
        response = super().form_valid(form)
        username = form.cleaned_data["username"]
        password = form.cleaned_data["password1"]
        user = authenticate(self.request, username=username, password=password)
        login(self.request, user)
        return response


class UserProfileView(LoginRequiredMixin, TemplateView):
    template_name = "accounts/profile.html"

tweets/views.py
from django.conf import settings
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.urls import reverse_lazy
from django.views.generic import CreateView, DeleteView, DetailView, ListView

from tweets.forms import CreateTweetForm

from .models import Tweet


class HomeView(LoginRequiredMixin, ListView):
    model = Tweet
    template_name = "tweets/home.html"
    context_object_name = "tweets"

    def get_queryset(self):
        return Tweet.objects.all().select_related("user").order_by("-created_at")


class TweetCreateView(LoginRequiredMixin, CreateView):
    model = Tweet
    form_class = CreateTweetForm
    template_name = "tweets/create.html"
    success_url = reverse_lazy(settings.LOGIN_REDIRECT_URL)

    def form_valid(self, form):
        form.instance.user = self.request.user
        return super().form_valid(form)


class TweetDetailView(LoginRequiredMixin, DetailView):
    model = Tweet
    template_name = "tweets/detail.html"
    context_object_name = "tweet"


class TweetDeleteView(UserPassesTestMixin, DeleteView):
    model = Tweet
    template_name = "tweets/delete.html"
    success_url = reverse_lazy(settings.LOGIN_REDIRECT_URL)

    def test_func(self):
        object = self.get_object()
        return object.user == self.request.user

welcome/views.py
from django.views.generic import TemplateView


class WelcomeView(TemplateView):
    template_name = "welcome/welcome.html"

templates/accounts/login.html
{% extends "base.html" %}

{% block title %}Login{% endblock %}

{% block content %}
<form method="post">
    {{ form.as_p }}
    {% csrf_token %}
    <button type="submit">ログイン</button>
</form>
{% endblock %}

templates/accounts/profile.html
{% extends "base.html" %}

{% block title %}Home{% endblock %}

{% block content %}
<h1>プロフィール</h1>
<h2>{{ user.username }}</h2>
{% endblock %}

templates/accounts/signup.html
{% extends "base.html" %}

{% block title %}Sign Up{% endblock %}

{% block content %}
<form method="post">
    {{ form.as_p }}
    {% csrf_token %}
    <button type="submit">ユーザー登録</button>
</form>
{% endblock %}

templates/base.html
<!DOCTYPE html>
<html lang="ja">

<head>
  <meta charset="UTF-8" />
  <title>{% block title %}Twitter Clone{% endblock%}</title>
</head>

<body>
  {% block content %}
  {% endblock %}
</body>

</html>

templates/tweets/create.html
{% extends "base.html" %}

{% block title %}Home{% endblock %}

{% block content %}
<form method="POST">
    {{ form.as_p}}
    {% csrf_token %}
    <button type="submit">ツイート</button>
</form>
{% endblock %}

templates/tweets/delete.html
{% extends "base.html" %}

{% block title %}Home{% endblock %}

{% block content %}
{% if tweet_delete.user == request.user %}
<h1>このツイートを削除しますか？</h1>
<p>Username: {{ tweet.user.username }}</p>
<p>Content: {{ tweet.content }}</p>
<p>Created at: {{ tweet.created_at }}</p>
<form method="POST">
    {{ form.as_p}}
    {% csrf_token %}
    <button type="submit">削除</button>
</form>
<a href="{% url 'tweets:home' %}">ホームに戻る</a>
{% endif %}
{% endblock %}

templates/tweets/detail.html
{% extends "base.html" %}

{% block title %}Home{% endblock %}

{% block content %}
<p>Username: {{ tweet.user.username }}</p>
<p>Content: {{ tweet.content }}</p>
<p>Created at: {{ tweet.created_at }}</p>

{% if tweet.user == request.user %}
<a href="{% url 'tweets:delete' pk=tweet.pk %}">このツイートを削除する</a>
{% endif %}

<a href="{% url 'tweets:home' %}">ホームに戻る</a>
{% endblock %}

templates/tweets/home.html
{% extends "base.html" %}

{% block title %}Home{% endblock %}

{% block content %}
<h1>Home</h1>
<a href="{% url 'tweets:create' %}">ツイートする</a>
<a href="{% url 'accounts:user_profile' username=user.username %}">プロフィール</a>
{% for tweet in tweets %}
<li>
    <p><a href="{% url 'accounts:user_profile' username=tweet.user %}">{{ tweet.user.username }}</a></p>
    <p><a href="{% url 'tweets:detail' pk=tweet.pk %}">{{ tweet.content }}</a></p>
    <p>{{ tweet.created_at }}</p>
</li>
{% endfor %}
{% endblock %}

templates/welcome/welcome.html
{% extends "base.html" %}